invoiceGenerator/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::get('/dashboard', 'InvoiceController@form');
Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/register', 'UserController@index');
Route::post('register', 'UserController@Register');
Route::get('Updaterole', 'UserController@Updaterole');
Route::resource('invoices', 'InvoiceController');

Route::resource('customers', 'CustomerController');

Route::get('/taxes' , 'TaxController@index');
Route::get('/save' , 'TaxController@save');

Route::get('printToPDF/{invoice_id}', 'InvoiceController@printToPDF')->name('printToPDF');

 Route::resource('payments', 'PaymentController');

invoiceGenerator/app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = [
        'invoice_no', 'invoice_date', 'due_date',
        'title', 'sub_total', 'discount',
        'grand_total', 'client_id',
        'user_id', 'invoice_id'
    ];

    public function products()
    {
        return $this->hasMany(InvoiceProduct::class);
    }
     public function user()
    {
        return $this->belongsTo(User::class);   
    }
    
    public static function findByinvoiceidOrFail(
        $invoice_id,
        $columns = array('*')
    ) {
        if ( ! is_null($invoice = static::whereInvoiceId($invoice_id)->first($columns))) {
            return $invoice;
        }

        throw new ModelNotFoundException;
    }
}

invoiceGenerator/app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App;
use PDF;
use Ramsey\Uuid\Uuid;
use DB;
use Auth;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Invoice;
use App\InvoiceProduct;
use App\Customer;

class InvoiceController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function form()
    {
//        $userRole = DB::table('role_user')
//                    ->where('user_id', '=', Auth::user()->id)
//                    ->join('roles', 'role_user.role_id', '=', 'roles.id')
//                    ->select('roles.name')
//                    ->first();
        //echo json_encode($userRole->name);
        //echo(Auth::user());
        //die();
      if (Auth::user()->hasRole(['Owner', 'Admin']))
      {
        
        $usr=DB::table('users')->get();
        $rol=DB::table('roles')->get();
        $userRoles=DB::table('users')->join('role_user', 'users.id', '=', 'role_user.user_id')
        ->join('roles', 'role_user.role_id', '=', 'roles.id')->select('users.*', 'roles.display_name', 'role_user.*')->get();

        return view('Users.Admin.dashboard')->with('data',$rol)->with('usrdata',$usr)->with('usrrol',$userRoles);
       }
        else 
        {
            return view('Users.Client.dashboard');
        }
    }

    public function index()
    {
        $invoices = Invoice::orderBy('created_at', 'desc')->where('user_id' , Auth::user()->userid)
            ->paginate(8);
       

        return view('invoices.index', compact('invoices'));
        
       
    }

    public function create()
    {
         $taxes=DB::table('taxes')->where('user_id' , Auth::user()->userid)->get();
         $customers= DB::table('customers')->where('user_id' , Auth::user()->userid)->get();

        return view('invoices.create')
        ->with(compact('customers'))
        ->with(compact('taxes'));
    }

    public function store(Request $request)
    {   

        // echo('here');
        // die();
        $invoiceid = Uuid::uuid4();
        $invoice_id = $invoiceid->toString();
        $userid=Auth::user()->userid;
        
        $this->validate($request, [
            'invoice_no' => 'required|alpha_dash|unique:invoices',
            'client_id' => 'required|max:255',
            'invoice_date' => 'required|date_format:Y-m-d',
            'due_date' => 'required|date_format:Y-m-d',
            'title' => 'required|max:255',
            'discount' => 'required|numeric|min:0',
            'products.*.name' => 'required|max:255',
            'products.*.price' => 'required|numeric|min:1',
            'products.*.qty' => 'required|integer|min:1'
        ]);
        
        if(!count($request->products)) {
            return response()
            ->json([
                'products_empty' => ['One or more Product is required.']
            ], 422);
        }

        $products = collect($request->products)->transform(function($product) {
            $product['total'] = $product['qty'] * $product['price'];
            $product['invoice_id'] ='temp invoice';
               return new InvoiceProduct($product);
        });

        foreach ($products as $p) {
            $p['invoice_id'] = $invoice_id;
        }
        $data = $request->except('products');
        
        $data['invoice_id']= $invoice_id;
        $data['user_id'] = $userid;
        $data['sub_total'] = $products->sum('total');
        $data['grand_total'] = $data['sub_total'] - $data['discount'];
//         try{
      
        $invoice = Invoice::create($data);
        $t=time();
        
        foreach ($products as $p) {
            // echo($p->invoice_id));
            // die();
            DB::table('invoice_products')->insert([
            'invoice_id'=>$p->invoice_id,
            'name'=>$p->name,
            'qty'=>$p->qty,
            'price'=>$p->price,
            'tax'=>$p->tax,
            'total'=>$p->total,
            'created_at'=>date('m/d/Y h:i:s a', $t)
            ]);
            //echo json_encode($product);
        }
        //die();
       
            //$invoice->products()->saveMany($products);
//        }
//        catch(Exception $e){
//            echo json_encode($e);
//            die();
//        }

        return response()
            ->json([
                'created' => true,
                'invoice_id' => $invoice->invoice_id
            ]);
    }

    public function show($invoice_id)
    {
        $invoice = Invoice::findByinvoiceidOrFail($invoice_id);
        $products = InvoiceProduct::findByinvoiceidOrFail($invoice_id);
        $invoice['products']=$products;
        return view('invoices.show', compact('invoice'));
    }

    public function edit($invoice_id)
    {
        $invoice = Invoice::findByinvoiceidOrFail($invoice_id);
        $products = InvoiceProduct::findByinvoiceidOrFail($invoice_id);
        $invoice['products']=$products;
        return view('invoices.edit', compact('invoice'));
    }

    public function update(Request $request, $invoice_id)
    {
        
    
        $this->validate($request, [
            'invoice_no' => 'required|alpha_dash|unique:invoices,invoice_no,'.$invoice_id.',invoice_id',
            'client_id' => 'required|max:255',
            'invoice_date' => 'required|date_format:Y-m-d',
            'due_date' => 'required|date_format:Y-m-d',
            'title' => 'required|max:255',
            'discount' => 'required|numeric|min:0',
            'products.*.name' => 'required|max:255',
            'products.*.price' => 'required|numeric|min:1',
            'products.*.qty' => 'required|integer|min:1'
        ]);

        $invoice = Invoice::findByinvoiceidOrFail($invoice_id);

        $products = collect($request->products)->transform(function($product) {
            $product['total'] = $product['qty'] * $product['price'];
            return new InvoiceProduct($product);
        });

       if(!count($request->products)) {
            return response()
            ->json([
                'products_empty' => ['One or more Product is required.']
            ], 422);
        }

        $data = $request->except('products');
        $data['sub_total'] = $products->sum('total');
        $data['grand_total'] = $data['sub_total'] - $data['discount'];

        $invoice->update($data);

        InvoiceProduct::where('invoice_id', $invoice->invoice_id)->delete();
        
        $t=time();
        

        foreach ($products as $p) {
            echo(json_encode($p));
            die();
            DB::table('invoice_products')->insert([
            'invoice_id'=>$p->invoice_id,
            'name'=>$p->name,
            'qty'=>$p->qty,
            'tax'=>$p->tax,
            'price'=>$p->price,
            'total'=>$p->total,
            // 'created_at'=>date("'m/d/Y h:i:s a'",$t),
            // 'updated_at'=>date("'m/d/Y h:i:s a'",$t)
            ]);
        }

        return response()
            ->json([
                'updated' => true,
                'invoice_id' => $invoice->invoice_id
            ]);
    }

    public function destroy($invoice_id)
    {
        $invoice = Invoice::findByinvoiceidOrFail($invoice_id);

        InvoiceProduct::where('invoice_id', $invoice->invoice_id)
            ->delete();

        $invoice->delete();

        return redirect()
            ->route('invoices.index');
    }
    
    public function printToPDF($invoice_id)
    {
//        $pdf = App::make('dompdf.wrapper');
//        $pdf->loadHTML('<h1>Test</h1>');
//        return $pdf->stream();
       
        $invoice = Invoice::findByinvoiceidOrFail($invoice_id);
        
        $products = InvoiceProduct::findByinvoiceidOrFail($invoice_id);
        
        $invoice['products']=$products;
        
        $pdf = PDF::loadView('invoices.invoice', compact('invoice'));

        return $pdf->stream();
        
        // return $pdf->download($invoice_id.'.pdf');
    }
    
}

invoiceGenerator/resources/views/invoices/create.blade.php
@extends('layouts.client')
@push('css')
<link rel="stylesheet" type="text/css" href="{{URL::asset('css/override.css')}}">
    <link rel="stylesheet" type="text/css" href="{{URL::asset('css/app.css')}}">

@endpush
@section('content')
    <div id="invoice">
        <div class="panel panel-default" v-cloak>
            <div class="panel-heading">
                <div class="clearfix">
                    <span class="panel-title">Create Invoice</span>

                    <a href="{{route('invoices.index')}}" class="btn btn-default pull-right">Back</a>
                </div>
            </div>
            <div class="panel-body">
                @include('invoices.form')
            </div>
            <div class="panel-footer">
                <a href="{{route('invoices.index')}}" class="btn btn-default">CANCEL</a>
                <button class="btn btn-success" @click="create" :disabled="isProcessing">CREATE</button>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{URL::asset('assets/js/jquery.js')}}"></script>
    <script src="{{URL::asset('assets/js/bootstrap.min.js')}}"></script>
    <script class="include" type="text/javascript" src="{{URL::asset('assets/js/jquery.dcjqaccordion.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.scrollTo.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/slidebars.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{URL::asset('assets/js/respond.min.js')}}" ></script>
    
    <!--common script for all pages-->
    <script src="{{URL::asset('assets/js/common-scripts.js')}}"></script>
    <script src="/js/vue.min.js"></script>
    <script src="/js/vue-resource.min.js"></script>

    <script type="text/javascript">
        Vue.http.headers.common['X-CSRF-TOKEN'] = '{{csrf_token()}}';

         window._form = {
            invoice_no: '',
            client: '',
            client_address: '',
            title: '',
            invoice_date: '',
            due_date: '',
            discount: 0,
            products: [{
                name: '',
                price: 0,
                qty: 1
            }]
        };
    </script>
    <script src="/js/app.js"></script>
    <script src="/js/allfunctions.js"></script>
@endpush

invoiceGenerator/resources/views/invoices/edit.blade.php
@extends('layouts.client')

@section('content')
    <div id="invoice">
        <div class="panel panel-default" v-cloak>
            <div class="panel-heading">
                <div class="clearfix">
                    <span class="panel-title">Create Invoice</span>
                    <a href="{{route('invoices.index')}}" class="btn btn-default pull-right">Back</a>
                </div>
            </div>
            <div class="panel-body">
                @include('invoices.form')
            </div>
            <div class="panel-footer">
                <a href="{{route('invoices.index')}}" class="btn btn-default">CANCEL</a>
                <button class="btn btn-success" @click="update" :disabled="isProcessing">UPDATE</button>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{URL::asset('assets/js/jquery.js')}}"></script>
    <script src="{{URL::asset('assets/js/bootstrap.min.js')}}"></script>
    <script class="include" type="text/javascript" src="{{URL::asset('assets/js/jquery.dcjqaccordion.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.scrollTo.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/slidebars.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{URL::asset('assets/js/respond.min.js')}}" ></script>

    <!--common script for all pages-->
    <script src="{{URL::asset('assets/js/common-scripts.js')}}"></script>
    <script src="{{URL::asset('js/vue.min.js')}}"></script>
    <script src="{{URL::asset('js/vue-resource.min.js')}}"></script>
    <script type="text/javascript">
        Vue.http.headers.common['X-CSRF-TOKEN'] = '{{csrf_token()}}';

        window._form = {!! $invoice->toJson() !!};
    </script>
    <script src="{{URL::asset('js/app.js')}}"></script>
@endpush

invoiceGenerator/resources/views/invoices/form.blade.php
<div class="row">
    <div class="col-sm-4">
        <div class="form-group">
            <label>Invoice No.</label>
            <input type="text" class="form-control" v-model="form.invoice_no">
            <p v-if="errors.invoice_no" class="error">@{{errors.invoice_no[0]}}</p>
        </div>
        <div class="form-group ">
            <label>Client</label>
            <!-- <input type="text" class="form-control" v-model="form.client"> -->
            <select id="customer_id" class="form-control" v-model="form.client_id">
                <?php
                    foreach ($customers as $r) 
                    {
                            ?>
                            <option value="<?= $r->customer_id ?>"><?= $r->customer_name?></option>
                            <?php
                                         
                    }

                  ?>
            </select>
            <p v-if="errors.client" class="error">@{{errors.client[0]}}</p>
        </div>
    </div>

    <div class="col-sm-4">
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" v-model="form.title">
            <p v-if="errors.title" class="error">@{{errors.title[0]}}</p>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <label>Invoice Date</label>
                <input type="date" class="form-control" v-model="form.invoice_date">
                <p v-if="errors.invoice_date" class="error">@{{errors.invoice_date[0]}}</p>
            </div>
            <div class="col-sm-6">
                <label>Due Date</label>
                <input type="date" class="form-control" v-model="form.due_date">
                <p v-if="errors.due_date" class="error">@{{errors.due_date[0]}}</p>
            </div>
        </div>
    </div>
</div>
<hr>
<div v-if="errors.products_empty">
    <p class="alert alert-danger">@{{errors.products_empty[0]}}</p>
    <hr>
</div>
<table class="table table-bordered table-form">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Qty</th>
            <th>tax</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <tr v-for="product in form.products">
            <td class="table-name" :class="{'table-error': errors['products.' + $index + '.name']}">
                <textarea class="table-control" v-model="product.name"></textarea>
            </td>
            <td class="table-price" :class="{'table-error': errors['products.' + $index + '.price']}">
                <input type="text" class="table-control"  v-model="product.price">
            </td>
            <td class="table-qty" :class="{'table-error': errors['products.' + $index + '.qty']}">
                <input type="text" class="table-control" v-model="product.qty">
            </td>

             <td class="table-tax" :class="{'table-error': errors['products.' + $index + '.tax']}">
                <select class="table-control" v-model="product.tax">
                <?php
                    foreach ($taxes as $t) 
                    {
                            ?>
                            <option value="<?= $t->tax ?>"><?= $t->name?><?= $t->tax?>%</option>
                            <?php
                                         
                    }

                  ?>
            </select>
            </td>
            <td class="table-total">
                <span class="table-text">@{{product.qty * product.price}}</span>
            </td>
            <td class="table-remove">
                <span @click="remove(product)" class="table-remove-btn">&times;</span>
            </td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td class="table-empty" colspan="3">
                <span @click="addLine" class="table-add_line">Add Line</span>
            </td>
            <td class="table-label">Sub Total</td>
            <td class="table-amount">@{{subTotal}}</td>
        </tr>
        <tr>
            <td class="table-empty" colspan="3">
                <input type="checkbox" id="checkbox" v-model="checked">
                <label for="checkbox">@{{message}}</label>
            </td>
            <td class="table-label">Discount</td>
            <td class="table-discount" :class="{'table-error': errors.discount}">
                <input type="text" class="table-discount_input" v-model="form.discount">
            </td>
        </tr>
        <tr>
            <td class="table-empty" colspan="3"></td>
            <td class="table-label">Grand Total</td>
            <td class="table-amount">@{{grandTotal}}</td>
        </tr>
    </tfoot>
</table>

invoiceGenerator/resources/views/invoices/index.blade.php
@extends('layouts.client')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="clearfix">
                <span class="panel-title">Invoices</span>
                <a href="{{route('invoices.create')}}" class="btn btn-success pull-right">Create</a>
            </div>
        </div>
        <div class="panel-body">
            @if($invoices->count())
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Invoice No.</th>
                        <th>Grand Total</th>
                        <th>Client</th>
                        <th>Invoice Date</th>
                        <th>Due Date</th>
                        <th colspan="2">Created At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($invoices as $invoice)
                        <tr>
                            <td>{{$invoice->invoice_no}}</td>
                            <td>{{$invoice->grand_total}}</td>
                            <td>{{$invoice->client}}</td>
                            <td>{{$invoice->invoice_date}}</td>
                            <td>{{$invoice->due_date}}</td>
                            <td>{{$invoice->created_at->diffForHumans()}}</td>
                            <td class="text-right">
                             
                                <a href="{{route('invoices.show', $invoice->invoice_id)}}" class="btn btn-default btn-sm">View</a>
                                <a href="{{route('invoices.edit', $invoice->invoice_id)}}" class="btn btn-primary btn-sm">Edit</a>
                                <a href="{{route('printToPDF', $invoice->invoice_id)}}" class="btn btn-primary btn-sm">Print</a>


                                <form class="form-inline" method="post"
                                    action="{{route('invoices.destroy', $invoice->invoice_id)}}"
                                    onsubmit="return confirm('Are you sure?')"
                                >
                                    <input type="hidden" name="_method" value="delete">
                                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $invoices->render() !!}
            @else
                <div class="invoice-empty">
                    <p class="invoice-empty-title">
                        No Invoices were created.
                        <a href="{{route('invoices.create')}}">Create Now!</a>
                    </p>
                </div>
            @endif
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{URL::asset('assets/js/jquery.js')}}"></script>
    <script src="{{URL::asset('assets/js/bootstrap.min.js')}}"></script>
    <script class="include" type="text/javascript" src="{{URL::asset('assets/js/jquery.dcjqaccordion.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.scrollTo.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/slidebars.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{URL::asset('assets/js/respond.min.js')}}" ></script>

    <!--common script for all pages-->
    <script src="{{URL::asset('assets/js/common-scripts.js')}}"></script>

@endpush

invoiceGenerator/resources/views/invoices/show.blade.php
@extends('layouts.client')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="clearfix">
                <span class="panel-title">Invoice</span>
                <div class="pull-right">
                    <a href="{{route('invoices.index')}}" class="btn btn-default">Back</a>
                    <a href="{{route('invoices.edit', $invoice->invoice_id)}}" class="btn btn-primary">Edit</a>
                    <form class="form-inline" method="post"
                        action="{{route('invoices.destroy', $invoice->invoice_id)}}"
                        onsubmit="return confirm('Are you sure?')"
                    >
                        <input type="hidden" name="_method" value="delete">
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                        <input type="submit" value="Delete" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Invoice No.</label>
                        <p>{{$invoice->invoice_no}}</p>
                    </div>
                    <div class="form-group">
                        <label>Grand Total</label>
                        <p>{{$invoice->grand_total}}</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Client</label>
                        <p>{{$invoice->client}}</p>
                    </div>
                    <div class="form-group">
                        <label>Client Address</label>
                        <pre class="pre">{{$invoice->client_address}}</pre>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Title</label>
                        <p>{{$invoice->title}}</p>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Invoice Date</label>
                            <p>{{$invoice->invoice_date}}</p>
                        </div>
                        <div class="col-sm-6">
                            <label>Due Date</label>
                            <p>{{$invoice->due_date}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Qty</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($invoice->products as $product)
                        <tr>
                            <td class="table-name">{{$product->name}}</td>
                            <td class="table-price">{{$product->price}}</td>
                            <td class="table-qty">{{$product->qty}}</td>
                            <td class="table-total text-right">{{$product->qty * $product->price}}</td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td class="table-empty" colspan="2"></td>
                        <td class="table-label">Sub Total</td>
                        <td class="table-amount">{{$invoice->sub_total}}</td>
                    </tr>
                    <tr>
                        <td class="table-empty" colspan="2"></td>
                        <td class="table-label">Discount</td>
                        <td class="table-amount">{{$invoice->discount}}</td>
                    </tr>
                    <tr>
                        <td class="table-empty" colspan="2"></td>
                        <td class="table-label">Grand Total</td>
                        <td class="table-amount">{{$invoice->grand_total}}</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{URL::asset('assets/js/jquery.js')}}"></script>
    <script src="{{URL::asset('assets/js/bootstrap.min.js')}}"></script>
    <script class="include" type="text/javascript" src="{{URL::asset('assets/js/jquery.dcjqaccordion.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.scrollTo.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/slidebars.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{URL::asset('assets/js/respond.min.js')}}" ></script>

    <!--common script for all pages-->
    <script src="{{URL::asset('assets/js/common-scripts.js')}}"></script>
 
@endpush