invoiceGenerator/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::get('/dashboard', 'InvoiceController@form');
Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/register', 'UserController@index');
Route::post('register', 'UserController@Register');
Route::get('Updaterole', 'UserController@Updaterole');
Route::resource('invoices', 'InvoiceController');

Route::resource('customers', 'CustomerController');

Route::get('/taxes' , 'TaxController@index');
Route::get('/save' , 'TaxController@save');

Route::get('printToPDF/{invoice_id}', 'InvoiceController@printToPDF')->name('printToPDF');

 Route::resource('payments', 'PaymentController');

invoiceGenerator/app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $fillable = [
        'payment_method', 'payment_date', 'totalpayment', 'account_no', 'bankname' , 'cheque_no' , 
        'cheque_expdate', 'deposite_date'
    ];

    public function payment()
    {
        return $this->belongsTo(Invoice::class);
    }

   
    public static function findBypaymentidOrFail(
        $payment_id,
        $columns = array('*')
    ) {
        if ( ! is_null($payment= static::wherePaymentId($payment_id)->first($columns))) {
            return $payment;
        }

        throw new ModelNotFoundException;
    }
}

invoiceGenerator/app/Http/Controllers/PaymentController.php
<?php

namespace App\Http\Controllers;

use App;
use PDF;
use Ramsey\Uuid\Uuid;
use DB;
use Auth;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Invoice;
use App\Payment;
use App\Customer;

class PaymentController extends Controller
{
    

    public function __construct()
    {

        $this->middleware('auth');
    }


    public function index()
    {
         $payments = Payment::orderBy('created_at', 'desc')->where('user_id' , Auth::user()->userid);
         
         $customers = Customer::orderBy('created_at', 'desc')->where('user_id' , Auth::user()->userid);

          $invoices = Invoice::orderBy('created_at', 'desc')->where('user_id' , Auth::user()->userid);

        return view('payments.index' )
        ->with(compact('payments'))
        ->with(compact('customers'))
        ->with(compact('invoices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

invoiceGenerator/resources/views/payments/create.blade.php
@extends('layouts.client')

@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="clearfix">
                <span class="panel-title">Payments</span>
                <a href="{{route('payments.create')}}" class="btn btn-success pull-right">Create</a>
            </div>
        </div>
        <div class="panel-body">
            @if($payments->count())
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Address</th>
                        <th>Email</th>
                        <th>Description</th>
                        <th>Mobile Number</th>
                        <th colspan="2">Created At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($customers as $customer)
                        <tr>
                            <td>{{$customer->customer_name}}</td>
                            <td>${{$customer->customer_address}}</td>
                            <td>{{$customer->customer_email}}</td>
                            <td>{{$customer->description}}</td>
                            <td>{{$customer->mobile_no}}</td>
                            <td>{{$customer->created_at->diffForHumans()}}</td>
                            <td class="text-right">
                             
                                <a href="{{route('customers.edit', $customer)}}" class="btn btn-primary btn-sm">Edit</a>



                                <form class="form-inline" method="post"
                                    action="{{route('customers.destroy', $customer)}}"
                                    onsubmit="return confirm('Are you sure?')"
                                >
                                    <input type="hidden" name="_method" value="delete">
                                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                                    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $customers->render() !!}
            @else
                <div class="invoice-empty">
                    <p class="invoice-empty-title">
                        No Customer were created.
                        <a href="{{route('customers.create')}}">Create Now!</a>
                    </p>
                </div>
            @endif
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{URL::asset('assets/js/jquery.js')}}"></script>
    <script src="{{URL::asset('assets/js/bootstrap.min.js')}}"></script>
    <script class="include" type="text/javascript" src="{{URL::asset('assets/js/jquery.dcjqaccordion.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.scrollTo.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/slidebars.min.js')}}"></script>
    <script src="{{URL::asset('assets/js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{URL::asset('assets/js/respond.min.js')}}" ></script>

    <!--common script for all pages-->
    <script src="{{URL::asset('assets/js/common-scripts.js')}}"></script>

@endpush